# Generated by Django 5.1.7 on 2025-03-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.ManyToManyField(related_name='category_apps', to='marketplace.category'),
        ),
    ]
