# Generated by Django 5.1.7 on 2025-03-19 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_application_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'app_reviewed')},
        ),
    ]
