# Generated by Django 5.1.7 on 2025-04-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_payment_payer_alter_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card')], default='upi', max_length=4),
        ),
    ]
