# Generated by Django 5.1.7 on 2026-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_developer_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
