# Generated by Django 5.1.7 on 2026-10-02 19:53

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_expand_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='app_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
